image: docker:latest

# mostly taken from: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

variables:
    DOCKER_REPOSITORY: git-st.inf.tu-dresden.de:4567
    CONTAINER_RELEASE_IMAGE_FRONTEND: $DOCKER_REPOSITORY/stgroup/linc/fridolean/frontend:latest
    CONTAINER_TEST_IMAGE_FRONTEND: $DOCKER_REPOSITORY/stgroup/linc/fridolean/frontend:$CI_COMMIT_REF_NAME
    CONTAINER_RELEASE_IMAGE_BACKEND: $DOCKER_REPOSITORY/stgroup/linc/fridolean/backend:latest
    CONTAINER_TEST_IMAGE_BACKEND: $DOCKER_REPOSITORY/stgroup/linc/fridolean/backend:$CI_COMMIT_REF_NAME


stages:
    - build
    - test
    - release

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $DOCKER_REPOSITORY

build-FRONTEND:
    stage: build
    tags:
        - dockered
    script:
        - docker build --pull --target build-stage -t $CONTAINER_TEST_IMAGE_FRONTEND src/frontend
        - docker push $CONTAINER_TEST_IMAGE_FRONTEND

build-BACKEND:
    stage: build
    tags:
        - dockered
    script:
        - docker build --pull -t $CONTAINER_TEST_IMAGE_BACKEND src/backend
        - docker push $CONTAINER_TEST_IMAGE_BACKEND

test_FRONTEND:
  stage: test
  tags:
      - dockered
  script:
    - docker pull $CONTAINER_TEST_IMAGE_FRONTEND
    - docker run --entrypoint "/bin/bash" $CONTAINER_TEST_IMAGE_FRONTEND -c 'yarn install --production=false && CI=true; yarn test --coverage'
  allow_failure: true

test_BACKEND:
  stage: test
  tags:
      - dockered
  script:
    - docker pull $CONTAINER_TEST_IMAGE_BACKEND
    - docker run $CONTAINER_TEST_IMAGE_BACKEND bash -c 'yarn install --production=false && CI=true; yarn test --coverage'

release-image-FRONTEND:
    stage: release
    tags:
        - dockered
    script:
        - docker build --pull -t $CONTAINER_RELEASE_IMAGE_FRONTEND src/frontend
        - docker push $CONTAINER_RELEASE_IMAGE_FRONTEND
    only:
        - master

release-image-BACKEND:
    stage: release
    tags:
        - dockered
    script:
        - docker pull $CONTAINER_TEST_IMAGE_BACKEND
        - docker tag $CONTAINER_TEST_IMAGE_BACKEND $CONTAINER_RELEASE_IMAGE_BACKEND
        - docker push $CONTAINER_RELEASE_IMAGE_BACKEND
    only:
        - master
